/* ============================================================
   Generates src/components/ui/icon-paths.ts from Google's Material
   Symbols SVGs (@material-symbols/svg-400 and -600, rounded).

   Run: npm run icons

   Why generate instead of loading the icon font: only the icons
   listed below end up in the bundle, there is no network request and
   no FOUT, and the glyphs stay inline SVG — which is what the rest of
   the stylesheet is written against.

   This map is the single source of truth for the site's icon
   vocabulary. Add a row, run the script, and the name is available as
   <Icon name="..." /> with the type updated to match.

     fill: true   also pull the filled cut (for `filled` call sites)
     bold: true   also pull weight 600 (for `strokeWidth` >= 2.2)
   ============================================================ */

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

/* our name → Material Symbols name (+ extra cuts to pull) */
const ICONS = {
  home: 'home',
  book: 'menu_book',
  calendar: 'calendar_month',
  clipboard: 'content_paste',
  award: 'trophy',
  certificate: 'workspace_premium',
  bell: 'notifications',
  search: 'search',
  settings: 'settings',
  'chevron-left': 'chevron_left',
  'chevron-right': 'chevron_right',
  'chevron-down': 'keyboard_arrow_down',
  'arrow-right': 'arrow_forward',
  'arrow-up-right': 'arrow_outward',
  menu: 'menu',
  close: 'close',
  play: { name: 'play_arrow', fill: true },
  check: { name: 'check', bold: true },
  'check-circle': 'check_circle',
  circle: 'radio_button_unchecked',
  clock: 'schedule',
  user: 'person',
  users: 'group',
  filter: 'filter_alt',
  plus: 'add',
  minus: 'remove',
  external: 'open_in_new',
  download: 'download',
  chart: 'bar_chart',
  layers: 'layers',
  sun: 'light_mode',
  moon: 'dark_mode',
  panel: 'view_sidebar',
  more: 'more_horiz',
  alert: 'warning',
  flask: 'science',
  box: 'deployed_code',
  help: 'help',
  video: 'videocam',
  flame: 'local_fire_department',
  target: 'adjust',
  code: 'code',
  briefcase: 'work',
  spark: 'star_shine',
  shield: 'verified_user',
  rotate: 'refresh',
  mail: 'mail',
  message: 'chat_bubble',
  star: { name: 'star', fill: true },
  lock: 'lock',
  grid: 'grid_view',
  list: 'format_list_bulleted',
  command: 'keyboard_command_key',
}

/* Every glyph in the packages is a single <path d> on a 0 -960 960 960
   grid, so pulling the one attribute is enough. */
function pathOf(weight, file) {
  const svg = readFileSync(join(ROOT, 'node_modules', `@material-symbols/svg-${weight}`, 'rounded', `${file}.svg`), 'utf8')
  const d = svg.match(/ d="([^"]+)"/)
  if (!d) throw new Error(`no path in ${file}.svg (weight ${weight})`)
  return d[1]
}

const rows = Object.entries(ICONS).map(([key, spec]) => {
  const { name, fill, bold } = typeof spec === 'string' ? { name: spec } : spec
  const cuts = [`d: '${pathOf(400, name)}'`]
  if (fill) cuts.push(`f: '${pathOf(400, `${name}-fill`)}'`)
  if (bold) cuts.push(`b: '${pathOf(600, name)}'`)
  const prop = /^[a-z][a-z0-9]*$/i.test(key) ? key : `'${key}'`
  return `  ${prop}: {\n    /* ${name} */\n    ${cuts.join(',\n    ')},\n  },`
})

const out = `/* ============================================================
   GENERATED by scripts/build-icons.mjs — do not edit by hand.

   Google Material Symbols (Rounded), drawn on a 0 -960 960 960 grid.
   d = weight 400 · f = filled cut · b = weight 600

   To add or change an icon, edit the map in the script and run
   \`npm run icons\`.
   ============================================================ */

export interface IconCuts {
  /** weight 400 */
  d: string
  /** filled */
  f?: string
  /** weight 600 */
  b?: string
}

export const ICON_PATHS = {
${rows.join('\n')}
} satisfies Record<string, IconCuts>
`

writeFileSync(join(ROOT, 'src/components/ui/icon-paths.ts'), out)
console.log(`icon-paths.ts — ${rows.length} icons, ${(out.length / 1024).toFixed(1)} kB`)
